# Use an offical Python runtime as a parent Image
FROM python:3.12

LABEL maintainer="hasansattar650@gmail.com"

#Set the working directory in the container
WORKDIR /code

#Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /code
COPY . /code/

# Configuration to avoid creating virtual directories inside the container
RUN poetry config virtualenvs.create false

#Install dependencies including development ones
RUN poetry install

#Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the app CMD can be overridden when starting the container
CMD ["poetry","run","uvicorn","03_dev_containers.main:app", "--host","0.0.0.0","--port","8000","--reload"]





