# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\":\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\timage_url\x18\x02 \x03(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\"@\n\x0bImageCreate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\timage_url\x18\x02 \x03(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\"@\n\x0bImageUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\timage_url\x18\x02 \x03(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\"#\n\tImageList\x12\x16\n\x06images\x18\x01 \x03(\x0b\x32\x06.Image\"\x19\n\x0bImageDelete\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=15
  _IMAGE._serialized_end=73
  _IMAGECREATE._serialized_start=75
  _IMAGECREATE._serialized_end=139
  _IMAGEUPDATE._serialized_start=141
  _IMAGEUPDATE._serialized_end=205
  _IMAGELIST._serialized_start=207
  _IMAGELIST._serialized_end=242
  _IMAGEDELETE._serialized_start=244
  _IMAGEDELETE._serialized_end=269
# @@protoc_insertion_point(module_scope)
