# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\xae\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\x05\x12\x16\n\x0estock_quantity\x18\x06 \x01(\x05\x12\x10\n\x08image_id\x18\x07 \x01(\x05\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t\"\x8c\x01\n\rProductCreate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\x05\x12\x16\n\x0estock_quantity\x18\x06 \x01(\x05\x12\x10\n\x08image_id\x18\x07 \x01(\x05\"\x8c\x01\n\rProductUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\x05\x12\x16\n\x0estock_quantity\x18\x06 \x01(\x05\x12\x10\n\x08image_id\x18\x07 \x01(\x05\"\x1b\n\rProductDelete\x12\n\n\x02id\x18\x01 \x01(\x05\"\x9a\x01\n\x0cProductEvent\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12+\n\nevent_type\x18\x02 \x01(\x0e\x32\x17.ProductEvent.EventType\x12\x15\n\revent_payload\x18\x03 \x01(\t\"2\n\tEventType\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\")\n\x0bProductList\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Productb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=18
  _PRODUCT._serialized_end=192
  _PRODUCTCREATE._serialized_start=195
  _PRODUCTCREATE._serialized_end=335
  _PRODUCTUPDATE._serialized_start=338
  _PRODUCTUPDATE._serialized_end=478
  _PRODUCTDELETE._serialized_start=480
  _PRODUCTDELETE._serialized_end=507
  _PRODUCTEVENT._serialized_start=510
  _PRODUCTEVENT._serialized_end=664
  _PRODUCTEVENT_EVENTTYPE._serialized_start=614
  _PRODUCTEVENT_EVENTTYPE._serialized_end=664
  _PRODUCTLIST._serialized_start=666
  _PRODUCTLIST._serialized_end=707
# @@protoc_insertion_point(module_scope)
